# Generated by Django 5.2.6 on 2025-09-14 05:20

import cuentas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuario_cuit_usuario_telefono'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', cuentas.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
